version: '3'
services:

  mongodb:
    image: mongo
    container_name: mongodb
    command: mongod
    ports:
      - "27017:27017"

  assignment:
    build: .
    container_name: go-tuts
    image: assignment
    ports:
      - "8080:8080"
    environment:
      MONGODB_URL: 'mongodb'
      DATABASE_NAME: 'assignment'
      PORT: '8080'
    links:
      - mongodb
